name: Research Summarizer

on:
  push:
    branches:
      - main
      - '**'  # trigger on all branches
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4
      with:
        python-version: '3.10'  # Specify a concrete version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8  # Install both pytest and flake8

    - name: Lint with flake8
      run: flake8 .

    - name: Run tests
      run: pytest
